# Generated by Django 5.1.6 on 2025-02-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('assigned_students', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('course_preferred_1', models.CharField(max_length=50)),
                ('course_preferred_2', models.CharField(blank=True, max_length=50, null=True)),
                ('course_preferred_3', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission_enquiry.counsellor')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('last_qualification', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('documents', models.FileField(upload_to='supporting_documents/')),
                ('course_preferred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission_enquiry.course')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('offline', 'OFFLINE'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('payee_name', models.CharField(max_length=100)),
                ('admission_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission_enquiry.admissionform')),
            ],
        ),
    ]
