# Generated by Django 5.1.6 on 2025-02-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
